# Generated by Django 3.2 on 2021-12-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211229_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfood',
            old_name='username',
            new_name='user',
        ),
    ]
